server:
  port: 8087

spring:
  datasource:
    username: root
    password: Andy2234@163
    url: jdbc:mysql://192.168.67.136:3306/cateyes_data?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 1
    host: 192.168.67.136
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    pool:
      #连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接超时时间（毫秒）
      timeout: 300

mybatis:
  mapper-locations: classpath:org/bwf/study/mapper/*.xml
  typ-aliases-package: org.bwf.study.model
  configuration:
    map-underscore-to-camel-case: true

logging:
  # file: D:/log/cateye.log
  pattern:
    console: '%d{yyyy-MM-dd} [%thread] %-5level %logger{50} ----%msg%n'
    file: '%d{yyyy/MM/dd} === [%thread] == %-5level == %logger{50} == %msg%n'